# Generated by Django 4.0.4 on 2023-08-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('course', models.TextField(primary_key=True, serialize=False)),
                ('offeredIn', models.CharField(max_length=220)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='coursePage',
            fields=[
                ('kind', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('courses', models.ManyToManyField(blank=True, related_name='+', to='home.course')),
            ],
        ),
    ]
