# Generated by Django 4.0.4 on 2023-08-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_course_coursepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='skill',
            fields=[
                ('skill', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='coursepage',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='coursepage',
            name='extra',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='coursepage',
            name='intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='coursepage',
            name='moto',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='coursepage',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='+', to='home.skill'),
        ),
    ]
