# Generated by Django 4.0.4 on 2023-08-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_skill_coursepage_description_coursepage_extra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='catagory',
            fields=[
                ('catagory', models.CharField(max_length=250, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='catagories',
            field=models.ManyToManyField(blank=True, related_name='+', to='home.catagory'),
        ),
    ]
