# Generated by Django 4.0.4 on 2023-08-02 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_catagory_course_catagories'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.TextField()),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('location', models.TextField()),
                ('date', models.DateField()),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('image', models.FileField(upload_to='img/')),
                ('catagories', models.ManyToManyField(related_name='+', to='home.catagory')),
            ],
        ),
    ]
