# Generated by Django 4.0.4 on 2023-08-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alumni'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
