# Generated by Django 4.0.4 on 2023-08-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alumni_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='value',
            field=models.CharField(default='0', max_length=250),
        ),
    ]
