# Generated by Django 4.0.4 on 2023-08-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_alumni_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('name', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('picture', models.FileField(upload_to='img/')),
                ('position', models.CharField(max_length=250)),
                ('schedule', models.TextField(max_length=250)),
            ],
        ),
    ]
