# Generated by Django 4.0.4 on 2023-08-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='program',
            fields=[
                ('name', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('alwaysOpen', models.BooleanField(default=False)),
                ('start', models.DateField(blank=True)),
                ('end', models.DateField(blank=True)),
                ('image', models.FileField(blank=True, upload_to='img/')),
                ('madeFor', models.CharField(max_length=120)),
            ],
        ),
    ]
