# Generated by Django 4.0.4 on 2023-08-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='catagory',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
