# Generated by Django 4.0.4 on 2023-08-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_program_catagory'),
    ]

    operations = [
        migrations.CreateModel(
            name='clubs',
            fields=[
                ('club', models.CharField(max_length=125, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('image', models.FileField(upload_to='img/')),
                ('link', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='program',
        ),
    ]
