# Generated by Django 4.0.4 on 2023-08-04 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_clubs_requirement_delete_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubs',
            name='image',
        ),
    ]
