# Generated by Django 4.0.4 on 2023-08-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_expect_developingprogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='developingprogram',
            name='expects',
        ),
        migrations.AddField(
            model_name='developingprogram',
            name='dates',
            field=models.ManyToManyField(related_name='+', to='home.date'),
        ),
    ]
