# Generated by Django 4.0.4 on 2023-08-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_developingprogram_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developingprogram',
            name='dates',
            field=models.ManyToManyField(blank=True, related_name='+', to='home.date'),
        ),
    ]
