# Generated by Django 4.0.4 on 2023-08-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_developingprogram_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='curiousProgram',
            fields=[
                ('program', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='img/')),
                ('description', models.TextField()),
                ('openFor', models.CharField(max_length=250)),
                ('year', models.IntegerField()),
                ('hasSchedule', models.BooleanField(default=False)),
                ('schedule', models.ManyToManyField(related_name='+', to='home.schedule')),
            ],
        ),
    ]
