# Generated by Django 4.0.4 on 2023-08-04 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_schedule_curiousprogram'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curiousprogram',
            old_name='schedule',
            new_name='schedules',
        ),
    ]
