# Generated by Django 4.0.4 on 2023-08-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_curiousprogram_schedules_startedprogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='startedprogram',
            name='image',
            field=models.FileField(blank=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='startedprogram',
            name='when',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='startedprogram',
            name='who',
            field=models.TextField(),
        ),
    ]
