# Generated by Django 4.0.4 on 2023-08-04 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_startedprogram_image_alter_startedprogram_when_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startedprogram',
            name='hasSchedule',
        ),
        migrations.RemoveField(
            model_name='startedprogram',
            name='schedules',
        ),
    ]
