# Generated by Django 4.0.4 on 2023-08-04 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_remove_startedprogram_hasschedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startedprogram',
            name='year',
        ),
    ]
