# Generated by Django 4.0.4 on 2023-08-04 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_remove_startedprogram_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='startedProgram',
        ),
    ]
