# Generated by Django 4.0.4 on 2023-08-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_delete_startedprogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='startProgram',
            fields=[
                ('program', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='img/')),
                ('description', models.TextField(blank=True)),
                ('who', models.TextField(blank=True)),
                ('when', models.TextField(blank=True)),
            ],
        ),
    ]
