# Generated by Django 4.0.4 on 2023-08-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_startprogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='ventureProgram',
            fields=[
                ('program', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='img/')),
                ('description', models.TextField(blank=True)),
                ('hasRecieving', models.BooleanField(default=True)),
                ('who', models.TextField()),
                ('recievingStudent', models.ManyToManyField(related_name='st+', to='home.expect')),
                ('recievingSupervisor', models.ManyToManyField(related_name='s+', to='home.expect')),
            ],
        ),
    ]
