# Generated by Django 4.0.4 on 2023-08-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_ventureprogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='ventureprogram',
            name='application',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ventureprogram',
            name='recievingStudent',
            field=models.ManyToManyField(blank=True, related_name='st+', to='home.expect'),
        ),
        migrations.AlterField(
            model_name='ventureprogram',
            name='recievingSupervisor',
            field=models.ManyToManyField(blank=True, related_name='s+', to='home.expect'),
        ),
        migrations.AddField(
            model_name='ventureprogram',
            name='activities',
            field=models.ManyToManyField(blank=True, related_name='+', to='home.activity'),
        ),
    ]
