# Generated by Django 4.0.4 on 2023-08-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_activity_ventureprogram_application_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='prize',
            fields=[
                ('prize', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='rounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('hasDescription', models.BooleanField(default=False)),
                ('date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='competition',
            fields=[
                ('program', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='img/')),
                ('description', models.TextField(blank=True)),
                ('hasRounds', models.BooleanField(default=False)),
                ('hasPrize', models.BooleanField(default=False)),
                ('application', models.TextField(blank=True)),
                ('alumniRounds', models.ManyToManyField(related_name='a+', to='home.rounds')),
                ('prizes', models.ManyToManyField(blank=True, related_name='+', to='home.prize')),
                ('requirements', models.ManyToManyField(related_name='+', to='home.requirement')),
                ('studentsRounds', models.ManyToManyField(related_name='s+', to='home.rounds')),
            ],
        ),
    ]
