# Generated by Django 4.0.4 on 2023-08-05 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_prize_rounds_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='who',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rounds',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
