# Generated by Django 4.0.4 on 2023-08-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_remove_competition_alumnirounds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
