# Generated by Django 4.0.4 on 2023-08-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='member',
            name='isFaculty',
            field=models.BooleanField(default=False),
        ),
    ]
