# Generated by Django 4.0.4 on 2023-08-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_member_description_member_isfaculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.TextField(blank=True),
        ),
    ]
