# Generated by Django 4.0.4 on 2023-08-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_member_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='requiredForMinor',
            field=models.BooleanField(default=False),
        ),
    ]
