# Generated by Django 4.0.4 on 2023-08-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_course_capstone'),
    ]

    operations = [
        migrations.CreateModel(
            name='previousSpeaker',
            fields=[
                ('name', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('tite', models.TextField(blank=True)),
                ('image', models.FileField(upload_to='img/')),
            ],
        ),
    ]
