# Generated by Django 4.0.4 on 2023-08-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_previousspeaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='previousspeaker',
            name='orgImg',
            field=models.FileField(blank=True, upload_to='img/'),
        ),
    ]
