# Generated by Django 4.0.4 on 2023-08-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_notionlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='time',
            field=models.TimeField(blank=True, default=None),
        ),
    ]
