# Generated by Django 4.0.4 on 2023-08-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_date_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='date',
        ),
        migrations.AlterField(
            model_name='developingprogram',
            name='dates',
            field=models.ManyToManyField(blank=True, related_name='+', to='home.clubs'),
        ),
    ]
