# Generated by Django 4.0.4 on 2023-08-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_delete_date_alter_developingprogram_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='developingprogram',
            name='dates',
            field=models.ManyToManyField(blank=True, related_name='+', to='home.date'),
        ),
    ]
