# Generated by Django 4.0.4 on 2023-08-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_date_alter_developingprogram_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='time',
        ),
        migrations.AlterField(
            model_name='date',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
