# Generated by Django 4.0.4 on 2023-08-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_remove_date_time_alter_date_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='rounds',
            field=models.ManyToManyField(blank=True, related_name='+', to='home.rounds'),
        ),
    ]
