# Generated by Django 4.0.4 on 2023-08-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_competition_rounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='preview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='curiousprogram',
            name='preview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='developingprogram',
            name='preview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ventureprogram',
            name='preview',
            field=models.TextField(blank=True),
        ),
    ]
