# Generated by Django 4.0.4 on 2023-08-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_competition_preview_curiousprogram_preview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FairParticipant',
            fields=[
                ('name', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('industry', models.TextField()),
                ('description', models.TextField()),
                ('hiring', models.TextField()),
                ('image', models.FileField(upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='FairYear',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('members', models.ManyToManyField(blank=True, related_name='+', to='home.fairparticipant')),
            ],
        ),
        migrations.CreateModel(
            name='JobFair',
            fields=[
                ('program', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='img/')),
                ('description', models.TextField(blank=True)),
                ('preview', models.TextField(blank=True)),
                ('years', models.ManyToManyField(blank=True, related_name='+', to='home.fairyear')),
            ],
        ),
    ]
