# Generated by Django 4.0.4 on 2023-08-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_fairparticipant_fairyear_jobfair'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobfair',
            name='who',
            field=models.TextField(blank=True),
        ),
    ]
