# Generated by Django 4.0.4 on 2023-08-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_jobfair_who'),
    ]

    operations = [
        migrations.AddField(
            model_name='fairparticipant',
            name='link',
            field=models.TextField(blank=True),
        ),
    ]
